import type { TemplateId } from "@/types";
import { lazy, type ComponentType } from "react";
import type { TemplateProps } from "./types";

export type { TemplateProps };

export const TEMPLATE_COMPONENTS: Record<TemplateId, ComponentType<TemplateProps>> = {
  "habit-tracker": lazy(() => import("./HabitTracker")),
  "water-intake": lazy(() => import("./WaterIntake")),
  "mood-tracker": lazy(() => import("./MoodTracker")),
  "workout-log": lazy(() => import("./WorkoutLog")),
  "sleep-tracker": lazy(() => import("./SleepTracker")),
  "expense-logger": lazy(() => import("./ExpenseLogger")),
  "tip-calculator": lazy(() => import("./TipCalculator")),
  "bill-splitter": lazy(() => import("./BillSplitter")),
  "savings-goal": lazy(() => import("./SavingsGoal")),
  "todo-list": lazy(() => import("./TodoList")),
  "reading-list": lazy(() => import("./ReadingList")),
  "link-saver": lazy(() => import("./LinkSaver")),
  "daily-journal": lazy(() => import("./DailyJournal")),
  "goal-tracker": lazy(() => import("./GoalTracker")),
  "quiz-builder": lazy(() => import("./QuizBuilder")),
  "countdown-timer": lazy(() => import("./CountdownTimer")),
  "form-survey": lazy(() => import("./FormSurvey")),
  "flashcard-deck": lazy(() => import("./FlashcardDeck")),
  "data-table": lazy(() => import("./DataTable")),
  "custom-reminder": lazy(() => import("./CustomReminder")),
  "simon-says": lazy(() => import("./SimonSays")),
  "snake": lazy(() => import("./Snake")),
  "minesweeper": lazy(() => import("./Minesweeper")),
  "wordle-clone": lazy(() => import("./WordleClone")),
  "tic-tac-toe": lazy(() => import("./TicTacToe")),
  "memory-match": lazy(() => import("./MemoryMatch")),
  "rock-paper-scissors": lazy(() => import("./RockPaperScissors")),
  "number-guess": lazy(() => import("./NumberGuess")),
  "hangman": lazy(() => import("./Hangman")),
  "coin-flip": lazy(() => import("./CoinFlip")),
  "random-number": lazy(() => import("./RandomNumber")),
  "dice-roller": lazy(() => import("./DiceRoller")),
  "magic-8-ball": lazy(() => import("./Magic8Ball")),
  "spin-wheel": lazy(() => import("./SpinWheel")),
  "random-name-picker": lazy(() => import("./RandomNamePicker")),
  "decision-maker": lazy(() => import("./DecisionMaker")),
  "would-you-rather": lazy(() => import("./WouldYouRather")),
  "truth-or-dare": lazy(() => import("./TruthOrDare")),
  "fortune-cookie": lazy(() => import("./FortuneCookie")),
  "compliment-machine": lazy(() => import("./ComplimentMachine")),
  "unit-converter": lazy(() => import("./UnitConverter")),
  "bmi-calculator": lazy(() => import("./BmiCalculator")),
  "age-calculator": lazy(() => import("./AgeCalculator")),
  "loan-calculator": lazy(() => import("./LoanCalculator")),
  "compound-interest": lazy(() => import("./CompoundInterest")),
  "percentage-calc": lazy(() => import("./PercentageCalc")),
  "roman-numerals": lazy(() => import("./RomanNumerals")),
  "binary-hex": lazy(() => import("./BinaryHex")),
  "colour-contrast": lazy(() => import("./ColourContrast")),
  "password-generator": lazy(() => import("./PasswordGenerator")),
  "qr-generator": lazy(() => import("./QrGenerator")),
  "gradient-maker": lazy(() => import("./GradientMaker")),
  "colour-palette": lazy(() => import("./ColourPalette")),
  "pixel-art": lazy(() => import("./PixelArt")),
  "ascii-art": lazy(() => import("./AsciiArt")),
  "pomodoro-timer": lazy(() => import("./PomodoroTimer")),
  "kanban-board": lazy(() => import("./KanbanBoard")),
  "pros-cons-list": lazy(() => import("./ProsConsList")),
  "bucket-list": lazy(() => import("./BucketList")),
  "typing-speed-test": lazy(() => import("./TypingSpeedTest")),
  "breathing-exercise": lazy(() => import("./BreathingExercise")),
  "meeting-agenda": lazy(() => import("./MeetingAgenda")),
  "random-word": lazy(() => import("./RandomWord")),
  "fake-quote": lazy(() => import("./FakeQuote")),
  "excuse-generator": lazy(() => import("./ExcuseGenerator")),
} as Record<TemplateId, ComponentType<TemplateProps>>;
